# Generated by Django 4.1.7 on 2023-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_executed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('name', 'email', 'description', 'schedule_time')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_executed', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('name', 'phone_number', 'description', 'sender', 'schedule_time')},
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_executed', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=250)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment')),
                ('receiver_mail', models.EmailField(max_length=254)),
                ('sender_mail', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('name', 'subject', 'description', 'sender_mail', 'receiver_mail', 'schedule_time')},
            },
        ),
    ]
