# Generated by Django 4.1.7 on 2023-03-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='task_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
