# Generated by Django 4.1.7 on 2023-03-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0002_action_task_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'schedule_time', 'actions')},
        ),
    ]
