# Generated by Django 4.1.7 on 2023-03-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0003_alter_action_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
    ]
