# Generated by Django 4.1.7 on 2023-03-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0004_alter_action_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('name', 'schedule_time', 'actions')},
        ),
    ]
